name: Post-PR-Formater

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Terraform-fmt:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: terraform_fmt --all-files

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply terraform-fmt changes