name: PR Checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  Terraform-fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: 1st Pre Commit
        uses: pre-commit/action@v3.0.0
        with: 
          extra_args: terraform_fmt --all-files
        continue-on-error: true
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4